# Generated by Django 5.0.1 on 2024-01-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coupom',
            new_name='coupon',
        ),
    ]
