# Generated by Django 4.2.4 on 2023-09-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
