# Generated by Django 5.0.1 on 2024-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='26a4c42d-d07b-4ad0-bb9f-0ab1e512e933', max_length=100),
        ),
    ]
