# Generated by Django 5.0.1 on 2024-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='7efc9da2-3105-4625-bb3a-839cb2ce9ec3', max_length=100),
        ),
    ]
