# Generated by Django 5.0.1 on 2024-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='6ad3e714-94ab-42d5-a906-9ee84f6c43b8', max_length=100),
        ),
    ]
