# Generated by Django 5.0.1 on 2024-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='12506674-d910-445f-83b6-90679951afa5', max_length=100),
        ),
    ]
