# Generated by Django 5.0.1 on 2024-01-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='464d7649-0598-412e-a129-82541c9cd257', max_length=100),
        ),
    ]
