# Generated by Django 5.0.1 on 2024-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='b5f1b4ee-09e6-460b-8f55-6c138fd3ef98', max_length=100),
        ),
    ]
