# Generated by Django 5.0.1 on 2024-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='1c075490-62f0-43ed-822b-3f507af4a1f2', max_length=100),
        ),
    ]
