# Generated by Django 5.0.1 on 2024-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='fbaadbdb-1687-43dc-85d3-c6e3ed4dab03', max_length=100),
        ),
    ]
