# Generated by Django 5.0.1 on 2024-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='ecd6bcab-824b-40a9-a00c-05b80b567d1a', max_length=100, null=True),
        ),
    ]
