# Generated by Django 5.0.1 on 2024-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, default='d39554c3-8dcf-4170-a189-0ff55c16919f', max_length=100, null=True),
        ),
    ]
