# Generated by Django 5.0.1 on 2024-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
