# Generated by Django 5.0.1 on 2024-01-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_delivered_date_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('delivered', 'DELIVERED')], default='ordered', max_length=20),
        ),
    ]
