# Generated by Django 4.2.4 on 2023-09-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetainformation',
            name='product_measuring',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('KG', 'KG'), ('ML', 'ML')], max_length=100, null=True),
        ),
    ]
