# Generated by Django 4.2.4 on 2023-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_productmetainformation_product_measuring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetainformation',
            name='product_measuring',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('L', 'L'), ('ML', 'ML')], max_length=100, null=True),
        ),
    ]
